site_name:           Plasmo.jl
repo_url:            https://github.com/jalving/Plasmo.jl
site_description:    Description
site_author:         Jordan Jalving
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
#  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - A simple graph model: tutorials/simple_example.md
  # - Title 2: tutorials/page2.md
  # - Title 3: tutorials/page3.md
- Documentation:
  - Graph Functions: documentation/graph_functions.md
  # - Title 2: sec2/page2.md
  # - Title 3: sec2/page3.md
